baseURL: http://kreativ-im-keller.de/
languageCode: de-de
title: Kreativ im Keller
theme: PaperMod

params:
    dateFormat: "2. January 2006"
    profileMode:
        enabled: true
        #title: "<Title>" # optional default will be site title
        subtitle: "Deko und Geschenke"
        imageUrl: "img/logo.jpeg" # optional
        imageTitle: "Logo: Kreativ im Keller" # optional
        imageWidth: 290 # custom size
        imageHeight: 280 # custom size
        #buttons:
        #  - name: Archiv
        #    url: "/archiv"

    socialIcons: # optional
      #- name: "Facebook"
      #  url: "<link>"
      - name: "Instagram"
        url: "https://instagram.com/kreativ.im.keller"
      - name: "Github"
        url: "https://github.com/JMasak/kreativ-im-keller"